#!/bin/bash
#SBATCH --job-name=bedtools_intersect
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/pbsim/
echo "Number of mappings to Chiappello genome"
samtools view -c chiappello_mapped.bam
echo "Number of mappings with TE overlaps"
bedtools intersect -a chiappello_mapped.bam -b /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_RefTE_new.gff -u -bed | wc -l
echo "Number of annotated TEs"
wc -l /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_RefTE_new.gff
echo "Number of TEs with reads mapping to them"
bedtools intersect -a /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_RefTE_new.gff -b chiappello_mapped.bam -u -bed | wc -l
bedtools intersect -a /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_RefTE_new.gff -b chiappello_mapped.bam -c -bed > readsperte.bed
sort -k10 -n readsperte.bed > sorted.readsperte.bed
