#!/bin/bash
#SBATCH --job-name=bedtools_genomecov
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=72:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/global/home/users/pierrj/slurm_stdout/slurm-%j.out
#SBATCH --error=/global/home/users/pierrj/slurm_stderr/slurm-%j.out
cd /global/home/users/pierrj/git
git pull
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
samtools sort mergedandpe.G3_1A_bwamem.bam -o sorted.mergedandpe.G3_1A_bwamem.bam
bedtools genomecov -d -ibam sorted.mergedandpe.G3_1A_bwamem.bam > genomecoverage.mergedandpe.G3_1A_bwamem.bed
