#!/bin/bash
#SBATCH --job-name=blast
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes
makeblastdb -in Magnaporthe_oryzae.MG8.dna.toplevel.noMT.fa -dbtype nucl
blastn -query MAGGY.fasta -db Magnaporthe_oryzae.MG8.dna.toplevel.noMT.fa -out MAGGY_MG8.blast
