#!/bin/bash
#SBATCH --job-name=checksubreadcounts
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell_all
cd G3_1A
pwd
samtools view -c demux.bam
cd ../G3_1B_1
pwd
samtools view -c demux.bam
cd ../G3_1C
pwd
samtools view -c demux.bam
cd ../G3_2A
pwd
samtools view -c demux.bam
cd ../G3_2B
pwd
samtools view -c demux.bam
cd ../G3_2C
pwd
samtools view -c demux.bam
cd ../G3_3A
pwd
samtools view -c demux.bam
cd ../G3_3B_1
pwd
samtools view -c demux.bam
cd ../K11_1
pwd
samtools view -c demux.bam
cd ../K9_2
pwd
samtools view -c demux.bam
