#!/bin/bash
#SBATCH --job-name=checksubreadcounts
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/
cd SMRTcell1
echo "SMRTcell1 .bam subreads"
samtools view -c subreads.bam
echo "SMRTcell1 .sam subreads"
samtools view -c subreads.sam
cd ../SMRTcell2
echo "SMRTcell1 .bam subreads"
samtools view -c subreads.bam
echo "SMRTcell1 .sam subreads"
samtools view -c subreads.sam
cd ../SMRTcell3
echo "SMRTcell1 .bam subreads"
samtools view -c subreads.bam
echo "SMRTcell1 .sam subreads"
samtools view -c subreads.sam
