#!/bin/bash
#SBATCH --job-name=coverageplot
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell_all/G3_1A
awk '{print substr ($1, 11, 12)}' genomecoverage_G3_1A_perbase | awk '{print substr ($1, 1, 2)}' > contignames_genomecoverage_perbase
paste contignames_genomecoverage_perbase genomecoverage_G3_1A_perbase > perbase_w_contignames
awk '$1 <= 10 {print}' perbase_w_contignames > perbase_w_contignames_first10contigs
echo -e "SCAFFOLDNUM\tSCAFFOLD\tBASE\tCOUNT" | cat - perbase_w_contignames_first10contigs > perbase_w_contignames_first10contigs.txt
R CMD BATCH coverageplot.R
