#!/bin/bash
#SBATCH --job-name=magecc_smrtcell1_mapping
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd ~/scripts/ciderseq
python3 ciderseq.py --no-separation --no-alignment --no-annotation --no-phasing --format fastq deconcat_config.json /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/pbsim/pooled_pbsimreads.fastq
