#!/bin/bash
#SBATCH --job-name=doesntmatter
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/global/home/users/pierrj/slurm_stdout/slurm-%j.out
#SBATCH --error=/global/home/users/pierrj/slurm_stderr/slurm-%j.out
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina
mkdir ${sample}
cd ${sample}
find ../ -name "${sample}*R1*" | xargs -I '{}' mv {} ./${sample}_R1.fastq
find ../ -name "${sample}*R2*" | xargs -I '{}' mv {} ./${sample}_R2.fastq
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o trimmed.${sample}_R1.fastq -p trimmed.${sample}_R2.fastq ${sample}_R1.fastq ${sample}_R2.fastq
##FIX THIS REFERENCE TO SEQPREP
../SeqPrep/SeqPrep/SeqPrep -f trimmed.G3_1A_S118_L004_R1_001.fastq -r trimmed.G3_1A_S118_L004_R2_001.fastq -1 seqprep.trimmed.G3_1A_S118_L004_R1_001.fastq -2 seqprep.trimmed.G3_1A_S118_L004_R2_001.fastq -A AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -B AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -s merged.trimmed.G3_1A
