#!/bin/bash
#SBATCH --job-name=exactlytwicefilter
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
awk 'NR==FNR{a[$1, $3]++; next} a[$1, $3]==2' qualityfiltered.lengthfiltered.samechromosome.exactlytwice.reverseread1.G3_1A_bwamem.bam qualityfiltered.lengthfiltered.samechromosome.exactlytwice.reverseread1.G3_1A_bwamem.bam > finalsplitreads.reverseread1.G3_1A_bwamem.bam
