#!/bin/bash
#SBATCH --job-name=fastqc
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
fastqc trimmed.G3_1A_S118_L004_R1_001.fastq --outdir=fastqc_output
fastqc trimmed.G3_1A_S118_L004_R2_001.fastq --outdir=fastqc_output
