#!/bin/bash
#SBATCH --job-name=fastp
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
source activate python=2.7
fastp -i G3_1A_S118_L004_R1_001.fastq -I G3_1A_S118_L004_R2_001.fastq -o fastp.G3_1A_S118_L004_R1_001.fastq -O fastp.G3_1A_S118_L004_R2_001.fastq --adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m --merged_out=merged.fastp.G3_1A.fastq
