#!/bin/bash
#SBATCH --job-name=igvcount
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/global/home/users/pierrj/slurm_stdout/slurm-%j.out
#SBATCH --error=/global/home/users/pierrj/slurm_stderr/slurm-%j.out
igvtools count /global/scratch/users/pierrj/eccDNA/pipeline_tests/merging/parallel.confirmed.G3_1A.bed /global/scratch/users/pierrj/eccDNA/pipeline_tests/peaks_gone/illumina.unique.parallel.confirmed.G3_1A.bam.tdf /global/scratch/users/pierrj/references/guy11_genome_baoetal2017.fasta
igvtools count --includeDuplicates /global/scratch/users/pierrj/eccDNA/pipeline_tests/merging/parallel.confirmed.G3_1A.bed /global/scratch/users/pierrj/eccDNA/pipeline_tests/peaks_gone/includeDuplicates.illumina.unique.parallel.confirmed.G3_1A.bam.tdf /global/scratch/users/pierrj/references/guy11_genome_baoetal2017.fasta