#!/bin/bash
#SBATCH --job-name=illumina_mapping_verysensitive
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/
bowtie2 -k 1 --very-sensitive-local -p 24 -x guy11_genome_baoetal2017 -1 G3_1A_S118_L004_R1_001.fastq -2 G3_1A_S118_L004_R2_001.fastq -S G3_1A_aligned_sensitive
samtools view -S -b G3_1A_aligned_sensitive > G3_1A_aligned_sensitive.bam
samtools sort G3_1A_aligned_sensitive.bam -o G3_1A_aligned_sensitive.sorted.bam
samtools index G3_1A_aligned_sensitive.sorted.bam
