#!/bin/bash
#SBATCH --job-name=doesntmatter
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/global/home/users/pierrj/slurm_stdout/slurm-%j.out
#SBATCH --error=/global/home/users/pierrj/slurm_stderr/slurm-%j.out
cd $SLURM_SUBMIT_DIR
# mkdir ${sample}
if [ ${sample:0:2} = "IF" ]
then
cd ${sample}
total=$(samtools view -c -F 2048 sorted.mergedandpe.${sample}_bwamem.bam)
guy11=$(samtools view -c -F 2048 sorted.mergedandpe.${sample}_bwamem.bam $(cat /global/scratch/users/pierrj/references/guy11_genome_baoetal2017.contignames | tr "\n" " "))
rice=$(samtools view -c -F 2048 sorted.mergedandpe.${sample}_bwamem.bam $(cat /global/scratch/users/pierrj/references/ORSA_w_organelles.contignames | tr "\n" " "))
total_u=$(samtools view -q 1 -c -F 2048 sorted.mergedandpe.${sample}_bwamem.bam)
guy11_u=$(samtools view -q 1 -c -F 2048 sorted.mergedandpe.${sample}_bwamem.bam $(cat /global/scratch/users/pierrj/references/guy11_genome_baoetal2017.contignames | tr "\n" " "))
rice_u=$(samtools view -q 1 -c -F 2048 sorted.mergedandpe.${sample}_bwamem.bam $(cat /global/scratch/users/pierrj/references/ORSA_w_organelles.contignames | tr "\n" " "))

echo -e $sample'\t'$total'\t'$guy11'\t'$rice'\t'$total_u'\t'$guy11_u'\t'$rice_u >> /global/scratch/users/pierrj/eccDNA/pipeline_tests/normalization/IF_readsmapped
fi