#!/bin/bash
#SBATCH --job-name=knowneffectors
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell_all/
source activate python=2.7
for d in */ ; do 
    echo "$d"
    cd $d
    samtools view baoetal2017_mapped_forintersect.bam | grep 'SA:Z:' | cat <(samtools view -H baoetal2017_mapped_forintersect.bam) - | samtools view -b | bedtools intersect -b "stdin" -a /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/riceblast_effector_locations_plusstrand_curated.bed -bed -wa -c -f 1.0 | paste <(awk '{print $1}' /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/riceblast_effector_locations_plusstrand_curated_effectornames.bed) - > riceblast_effector_coverage_100_SRs
   cd ..
done
