#!/bin/bash
#SBATCH --job-name=maizedata_splitbam
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2_knl
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=72:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/maizepacbio/
samtools view -b m54179_180721_023318.subreads.bam | awk '{if(NR%4==0){print >> "bamsubreads.cp1.bam"} else if(NR%4==1){print >> "bamsubreads.cp2.bam"} else if(NR%4==2){print >> "bamsubreads.cp3.bam"} else if(NR%4==3){print >> "bamsubreads.cp4.bam"}}'
