#!/bin/bash
#SBATCH --job-name=fournode_ccs
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2_knl
#SBATCH --qos=savio_normal
#SBATCH --nodes=4
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/maizepacbio/
samtools view -H m54179_180721_023318.subreads.bam > rawsubreads.cp1.sam
for (( i = 2 ; i < 5; i++)); do cp rawsubreads.cp1.sam rawsubreads.cp$i.sam ; done
samtools view m54179_180721_023318.subreads.bam | awk '{if(NR%4==0){print >> "rawsubreads.cp1.sam"} else if(NR%4==1){print >> "rawsubreads.cp2.sam"} else if(NR%4==2){print >> "rawsubreads.cp3.sam"} else if(NR%4==3){print >> "rawsubreads.cp4.sam"}}'
srun --ntasks=1 samtools view -b rawsubreads.cp1.sam > rawsubreads.cp1.bam &
srun --ntasks=1 samtools view -b rawsubreads.cp2.sam > rawsubreads.cp2.bam &
srun --ntasks=1 samtools view -b rawsubreads.cp3.sam > rawsubreads.cp3.bam &
srun --ntasks=1 samtools view -b rawsubreads.cp4.sam > rawsubreads.cp4.bam &
wait
sleep 60
source activate python=2.7
srun --ntasks=1 ccs --reportFile=ccs_report_cp1.txt rawsubreads.cp1.bam cp1/maizeccs.cp1.bam &
srun --ntasks=1 ccs --reportFile=ccs_report_cp2.txt rawsubreads.cp2.bam cp2/maizeccs.cp2.bam &
srun --ntasks=1 ccs --reportFile=ccs_report_cp3.txt rawsubreads.cp3.bam cp3/maizeccs.cp3.bam &
srun --ntasks=1 ccs --reportFile=ccs_report_cp4.txt rawsubreads.cp4.bam cp4/maizeccs.cp4.bam &
wait
sleep 60
source deactivate
bamtools merge -in cp1/maizeccs.cp1.bam -in cp2/maizeccs.cp2.bam -in cp3/maizeccs.cp3.bam -in cp4/maizeccs.cp4.bam -out maizeccs_merged.bam
