#!/bin/bash
#SBATCH --job-name=fournode_ccs
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2_knl
#SBATCH --qos=savio_normal
#SBATCH --nodes=4
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/maizepacbio/
source activate python=2.7
srun --ntasks=1 --nodes=1 ccs --reportFile=ccs_report_combined0.txt combined0.bam combined0/maizeccs.combined0.bam &
srun --ntasks=1 --nodes=1 ccs --reportFile=ccs_report_combined1.txt combined1.bam combined1/maizeccs.combined1.bam &
srun --ntasks=1 --nodes=1 ccs --reportFile=ccs_report_combined2.txt combined2.bam combined2/maizeccs.combined2.bam &
srun --ntasks=1 --nodes=1 ccs --reportFile=ccs_report_combined3.txt combined3.bam combined3/maizeccs.combined3.bam &
wait
sleep 60
echo "done with ccs"
source deactivate
bamtools merge -in combined0/maizeccs.combined0.bam -in combined1/maizeccs.combined1.bam -in combined2/maizeccs.combined2.bam -in combined3/maizeccs.combined3.bam -out maizeccs_combined_merge.bam
echo "done merging"
samtools view -c maizeccs_combined_merge.bam
echo "done done"
