#!/bin/bash
#SBATCH --job-name=maizedataccs_demux_singleside
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2_knl
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=72:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/maizepacbio/
source activate python=2.7
lima --different --dump-removed --split-bam-named --ccs --single-side analysis_savio2_knl_singleside/maizeccs.bam ../../barcodes.fasta analysis_savio2_knl_singleside/maizeccs_demux.bam
source deactivate
