#!/bin/bash
#SBATCH --job-name=merge_all_three
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBTACH --output=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/finalmerge_output.txt
#SBATCH --error=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/finalmerge_error.txt
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/
mkdir SMRTcell_all
for line in $(cat barcodelist); do
    echo $line
    mkdir SMRTcell_all/barcode_$line
    bamtools merge -in SMRTcell1/demux.AJI_$line--OF_PacF$line.bam -in SMRTcell2_repeat/demux.AJI_$line--OF_PacF$line.bam -in SMRTcell3/demux.AJI_$line--OF_PacF$line.bam -out SMRTcell_all/barcode_$line/merged_demux.AJI_$line--OF_PacF$line.bam
    samtools view -c SMRTcell_all/barcode_$line/merged_demux.AJI_$line--OF_PacF$line.bam
done
