#!/bin/bash
#SBATCH --job-name=maizedata_ccs_singlenode
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=72:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/maizepacbio/splittingtaskspractice
source activate python=2.7
lima --different --dump-removed --split-bam-named --ccs --single-side maizeccs.cp1.bam ../../../barcodes.fasta cp1/maizeccs_demux.cp1.bam
lima --different --dump-removed --split-bam-named --ccs --single-side maizeccs.cp2.bam ../../../barcodes.fasta cp2/maizeccs_demux.cp2.bam
lima --different --dump-removed --split-bam-named --ccs --single-side maizeccs.cp3.bam ../../../barcodes.fasta cp3/maizeccs_demux.cp3.bam
lima --different --dump-removed --split-bam-named --ccs --single-side maizeccs.cp4.bam ../../../barcodes.fasta cp4/maizeccs_demux.cp4.bam
source deactivate
