#!/bin/bash
#SBATCH --job-name=novoalign
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/
novoalign -d guy11_genome_baoetal2017.nix -f G3_1A_S118_L004_R1_001.fastq G3_1A_S118_L004_R2_001.fastq -F ILM1.8 -o SAM -i PE 450,150 --mCPU 24 > G3_1A_novoalign.sam
