#!/bin/bash
#SBATCH --job-name=outward_facing
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
samtools view mergedandpe.G3_1A_bwamem.bam | awk '{ if (($2 == 83 || $2 == 147) && $9 > 0) print $0 ; else if (($2 == 99 || $2 == 163) && $9 <0) print $0}' | cat <(samtools view -H mergedandpe.G3_1A_bwamem.bam) - | samtools view -b -h - > outwardfacing.mergedandpe.G3_1A_bwamem.bam
samtools sort outwardfacing.mergedandpe.G3_1A_bwamem.bam -o sorted.outwardfacing.mergedandpe.G3_1A_bwamem.bam
samtools index sorted.outwardfacing.mergedandpe.G3_1A_bwamem.bam
