#!/bin/bash
#SBATCH --job-name=pcatables
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2_bigmem
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell_all/
for d in */ ; do 
    echo "$d"
    cd $d
    dirname=$(basename $d)
    awk '{print $4}' genomecoverage_normalized_w_scaffoldnames | cat <(echo "$dirname") - > table_for_PCA
    cd ..
done
cd G3_1A
awk '{print $1 "-" $3}' genomecoverage_normalized_w_scaffoldnames | cat <(echo "BASE") - > table_for_PCA_basenames
cd ..
cp G3_1A/table_for_PCA_basenames table_for_PCA_basenames
ls -d */ | xargs -I {} basename {} > dirlist
mapfile -t <dirlist
paste table_for_PCA_basenames "${MAPFILE[@]/%//table_for_PCA}" > final_table_for_PCA.txt
awk 'BEGIN { FS=OFS="\t" }
{
    for (rowNr=1;rowNr<=NF;rowNr++) {
        cell[rowNr,NR] = $rowNr
    }
    maxRows = (NF > maxRows ? NF : maxRows)
    maxCols = NR
}
END {
    for (rowNr=1;rowNr<=maxRows;rowNr++) {
        for (colNr=1;colNr<=maxCols;colNr++) {
            printf "%s%s", cell[rowNr,colNr], (colNr < maxCols ? OFS : ORS)
        }
    }
}' final_table_for_PCA.txt > transposed_final_table_for_PCA.txt
sed 9q transposed_final_table_for_PCA.txt > notest_transposed_final_table_for_PCA.txt
