#!/bin/bash
#SBATCH --job-name=rarefication_test
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell_all/G3_1C
source activate python=2.7
for i in {1000..82000..1000}; do
    samtools view demux.bam | shuf | head -$i > "$i".tmp
    cat <(samtools view -H demux.bam) "$i".tmp | samtools view -b > "$i"_header.tmp.bam
    pbmm2 align --preset CCS --sort /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/guy11_genome_baoetal2017.mmi "$i"_header.tmp.bam | bedtools genomecov -bg -ibam - | awk '$4 >= 10 {print}' | bedtools merge -d 1 | awk '{if ($3 - $2 >= 1000) {print $0}}' | wc -l &>> rarefy_hotspot_yaxis
    echo $i &>> rarefy_hotspot_xaxis
done
paste rarefy_hotspot_xaxis rarefy_hotspot_yaxis > rarefy_hotspot
echo -e "READCOUNT\tMICROECCS" | cat - rarefy_hotspot > rarefy_hotspot.txt
rm *.tmp.*
rm *.tmp
source deactivate
