#!/bin/bash
#SBATCH --job-name=sa_single
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
samtools view -f 80 mergedandpe.G3_1A_bwamem.bam | awk '{for (i=1;i<=NF;i++) {if ($i~/^SA:Z:/) {a=$i}} {if (gsub(/;/, "", a) == 1) print $0}}' | wc -l
samtools view -F 80 mergedandpe.G3_1A_bwamem.bam | awk '{for (i=1;i<=NF;i++) {if ($i~/^SA:Z:/) {a=$i}} {if (gsub(/;/, "", a) == 1) print $0}}' | wc -l
samtools view -f 80 mergedandpe.G3_1A_bwamem.bam | awk '{for (i=1;i<=NF;i++) {if ($i~/^SA:Z:/) {a=$i}} {if (gsub(/;/, "", a) == 1) print $0}}' | awk '{print $1}' | sort | uniq -u
samtools view -F 80 mergedandpe.G3_1A_bwamem.bam | awk '{for (i=1;i<=NF;i++) {if ($i~/^SA:Z:/) {a=$i}} {if (gsub(/;/, "", a) == 1) print $0}}' | awk '{print $1}' | sort | uniq -u
