#!/bin/bash
#SBATCH --job-name=samtoolsconvert
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=72:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/maizepacbio
samtools view m54179_180721_023318.subreads.bam > maizepacbio_rawdata_subreads.sam
