#!/bin/bash
#SBATCH --job-name=samtools_convert
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
samtools view -b -h <(cat <(samtools view -H G3_1A_bwamem.bam) finalsplitreads.reverseread1.G3_1A_bwamem.bam) > forexport.finalsplitreads.reverseadread1.G3_1A_bwamem.bam
samtools sort forexport.finalsplitreads.reverseadread1.G3_1A_bwamem.bam > sorted.forexport.finalsplitreads.reverseadread1.G3_1A_bwamem.bam
samtools index sorted.forexport.finalsplitreads.reverseadread1.G3_1A_bwamem.bam
