#!/bin/bash
#SBATCH --job-name=seqprep_discard
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
../SeqPrep/SeqPrep/SeqPrep -f G3_1A_S118_L004_R1_001.fastq -r G3_1A_S118_L004_R2_001.fastq -1 seqprep.disc.G3_1A_S118_L004_R1_001.fastq -2 seqprep.disc.G3_1A_S118_L004_R2_001.fastq -A AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -B AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -s merged.G3_1A -3 discarded.G3_1A_S118_L004_R1_001.fastq -4 discarded.G3_1A_S118_L004_R2_001.fastq
