#!/bin/bash
#SBATCH --job-name=singleendmapfile
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/illumina/G3_1A_tests
cat <(zcat seqprep.G3_1A_S118_L004_R1_001.fastq) <(zcat seqprep.G3_1A_S118_L004_R2_001.fastq) <(zcat merged.G3_1A) > forsingleendmapping.G3_1A.fastq
