#!/bin/bash
#SBATCH --job-name=SMRTcell1_single_node_ccs
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2_knl
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBTACH --output=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/singlenode_output.txt
#SBATCH --error=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/singlenode_error.txt
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/
mkdir SMRTcell1_copy
cp SMRTcell1/subreads.bam SMRTcell1_copy/subreads.bam
cd SMRTcell1_copy
source activate python=2.7
ccs --reportFile=ccs_report_smrtcell1_singlenode.txt subreads.bam ccs.bam
lima --different --dump-removed --split-bam-named --ccs ccs.bam /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/barcodes.fasta demux.bam
source deactivate
Rscript --vanilla ~/scripts/lima/report_detail.R demux.lima.report
mkdir detailgraphs
mv detail_* detailgraphs