#!/bin/bash
#SBATCH --job-name=split_file
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/maizepacbio/
total_lines=$(samtools view -c m54179_180721_023318.subreads.bam)
((lines_per_file = (total_lines + 4 - 1) / 4))
split --lines=${lines_perfile} -d --additional-suffix=.sam maizepacbio_rawdata_subreads.sam linesplit
samtools view -H maizepacbio_rawdata_subreads.sam > head.linesplit0.sam
for (( i = 1 ; i < 4; i++)); do cp head.linesplit0.sam head.linesplit$i.sam ; done
for (( i = 0 ; i < 4; i++)); do cat head.linesplit$i.sam linesplit0$i.sam > combined$i.sam ; done
for (( i = 0 ; i < 4; i++)); do samtools view -b combined$i.sam > combined$i.bam; done
