#!/bin/bash
#SBATCH --job-name=SMRTcell2_G3_1A_bedtools_intersect_genes
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBTACH --output=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell2/bedtools_genes_output.txt
#SBATCH --error=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell2/bedtools_tes_error.txt
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell2/G3_1A
source activate python=2.7
pbmm2 align --preset CCS --sort --log-level INFO /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_chiappello_genome.mmi demux.bam chiappello_mapped.bam
source deactivate
echo "Number of mappings to Chiappello genome"
samtools view -c chiappello_mapped.bam
echo "Number of mappings with gene overlaps"
bedtools intersect -a chiappello_mapped.bam -b /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_chiappello_eugeneannotation_justgene.gff -u -bed | wc -l
echo "Number of annotated genes"
wc -l /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_chiappello_eugeneannotation_justgene.gff
echo "Number of genes with reads mapping to them"
bedtools intersect -a /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_chiappello_eugeneannotation_justgene.gff -b chiappello_mapped.bam -u -bed | wc -l
bedtools intersect -a /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/GY11_chiappello_eugeneannotation_justgene.gff -b chiappello_mapped.bam -c -bed > readspergene.bed
sort -k10 -n readspergene.bed > sorted.readspergene.bed
