#!/bin/bash
#SBATCH --job-name=SMRTcell2_map_G3_1A
#SBATCH --account=fc_kvkallow
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --mail-user=pierrj@berkeley.edu
#SBATCH --mail-type=ALL
#SBTACH --output=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell2/map_G3_1A_output.txt
#SBATCH --error=/global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell2/map_G3_1A_error.txt
cd /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/rawdata/SMRTcell2
mkdir G3_1A
cp demux.AJI_17--OF_PacF17.bam G3_1A/demux.bam
cd G3_1A
source activate python=2.7
pbmm2 align --preset CCS --sort --log-level INFO --unmapped /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/B71_mitochondria.mmi demux.bam mitochondria_mapped.bam
source deactivate
bamtools split -mapped -in mitochondria_mapped.bam
echo "Total number of reads"
samtools view -c demux.bam
echo "Number of reads mapping to mitochondrial genome"
samtools view -c mitochondria_mapped.MAPPED.bam
echo "Number of reads mapping to other things"
samtools view -c mitochondria_mapped.UNMAPPED.bam
cp mitochondria_mapped.UNMAPPED.bam mitochondria_filtered.bam
source activate python=2.7
pbmm2 align --preset CCS --sort --log-level INFO --unmapped /global/scratch/users/pierrj/eccDNA/magnaporthe_pureculture/reference_genomes/guy11_genome_baoetal2017.mmi mitochondria_filtered.bam genome_mapped.bam
source deactivate
bamtools split -mapped -in genome_mapped.bam
echo "Number of reads that don't map to Guy11 genome"
samtools view -c genome_mapped.UNMAPPED.bam
echo "Number of reads that do map to Guy11 genome"
samtools view -c genome_mapped.MAPPED.bam
echo "Number of chimeric alignments"
samtools view genome_mapped.MAPPED.bam | grep 'SA:' | wc -l
